/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Sala221
 */
public class FormularioUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FormularioUsuario
     */
    public FormularioUsuarios() {
        initComponents();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGRoles = new javax.swing.ButtonGroup();
        jLNombre = new javax.swing.JLabel();
        jTextNomUsu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        j1 = new javax.swing.JCheckBox();
        j2 = new javax.swing.JCheckBox();
        j3 = new javax.swing.JCheckBox();
        j5 = new javax.swing.JCheckBox();
        j6 = new javax.swing.JCheckBox();
        j4 = new javax.swing.JCheckBox();
        j7 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLDocumento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextDocumento = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jBtCrear = new javax.swing.JButton();
        jBtVer = new javax.swing.JButton();
        jlFechaAsign = new javax.swing.JLabel();
        jDateChooserAsign = new com.toedter.calendar.JDateChooser();
        jlFechaRevoc = new javax.swing.JLabel();
        jDateChooserRevo = new com.toedter.calendar.JDateChooser();
        jlEstado = new javax.swing.JLabel();
        jComEstado = new javax.swing.JComboBox();
        jBtConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(795, 550));
        getContentPane().setLayout(null);

        jLNombre.setText("Nombre Usuario:");
        getContentPane().add(jLNombre);
        jLNombre.setBounds(400, 30, 110, 14);

        jTextNomUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNomUsuMouseClicked(evt);
            }
        });
        jTextNomUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomUsuActionPerformed(evt);
            }
        });
        jTextNomUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomUsuKeyTyped(evt);
            }
        });
        getContentPane().add(jTextNomUsu);
        jTextNomUsu.setBounds(510, 30, 180, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        j1.setText("Director");
        j1.setActionCommand("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setText("A. Coordinador");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setText("Abogado Asesor");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j5.setText("Monitor Judicante");

        j6.setText("Monitor Estudiante");

        j4.setText("Secretaria");

        j7.setText("E. Practicante");

        jPanel2.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j1)
                    .addComponent(j5))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j6)
                    .addComponent(j2))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j3)
                        .addGap(45, 45, 45)
                        .addComponent(j4))
                    .addComponent(j7))
                .addContainerGap(147, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j2)
                                .addComponent(j3)
                                .addComponent(j4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j5)
                            .addComponent(j6)
                            .addComponent(j7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 710, 110);

        jLDocumento.setText("Documento");
        getContentPane().add(jLDocumento);
        jLDocumento.setBounds(30, 30, 65, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 63, 699, 10);

        jTextDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDocumentoActionPerformed(evt);
            }
        });
        jTextDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextDocumento);
        jTextDocumento.setBounds(100, 30, 116, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 252, 699, 2);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuario);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 270, 654, 122);

        jBtCrear.setText("Crear");
        jBtCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jBtCrear);
        jBtCrear.setBounds(280, 400, 80, 30);

        jBtVer.setText("Ver");
        getContentPane().add(jBtVer);
        jBtVer.setBounds(390, 400, 70, 30);

        jlFechaAsign.setText("Fecha Asignación:");
        getContentPane().add(jlFechaAsign);
        jlFechaAsign.setBounds(200, 200, 96, 14);

        jDateChooserAsign.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(jDateChooserAsign);
        jDateChooserAsign.setBounds(300, 200, 117, 20);

        jlFechaRevoc.setText("Fecha Revocación:");
        getContentPane().add(jlFechaRevoc);
        jlFechaRevoc.setBounds(450, 200, 91, 14);
        getContentPane().add(jDateChooserRevo);
        jDateChooserRevo.setBounds(560, 200, 111, 20);

        jlEstado.setText("Estado:");
        getContentPane().add(jlEstado);
        jlEstado.setBounds(30, 200, 46, 14);

        jComEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(jComEstado);
        jComEstado.setBounds(90, 200, 100, 20);

        jBtConsulta.setText("Consultar");
        getContentPane().add(jBtConsulta);
        jBtConsulta.setBounds(230, 23, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomUsuActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void jTextDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDocumentoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextDocumentoActionPerformed

    private void jTextDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDocumentoKeyTyped
        char  c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();

        String cadena = jTextDocumento.getText();
        if(cadena.length()>=11)evt.consume();
    }//GEN-LAST:event_jTextDocumentoKeyTyped

    private void jBtCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtCrearActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        this.jTableUsuario.setEnabled(false);
    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jTextNomUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNomUsuMouseClicked
          this.jTextNomUsu.setEditable(false);  

    }//GEN-LAST:event_jTextNomUsuMouseClicked

    private void jTextNomUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomUsuKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextNomUsuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioUsuarios().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGRoles;
    public javax.swing.JCheckBox j1;
    public javax.swing.JCheckBox j2;
    public javax.swing.JCheckBox j3;
    public javax.swing.JCheckBox j4;
    public javax.swing.JCheckBox j5;
    public javax.swing.JCheckBox j6;
    public javax.swing.JCheckBox j7;
    public javax.swing.JButton jBtConsulta;
    public javax.swing.JButton jBtCrear;
    public javax.swing.JButton jBtVer;
    public javax.swing.JComboBox jComEstado;
    public com.toedter.calendar.JDateChooser jDateChooserAsign;
    public com.toedter.calendar.JDateChooser jDateChooserRevo;
    private javax.swing.JLabel jLDocumento;
    private javax.swing.JLabel jLNombre;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTable jTableUsuario;
    public javax.swing.JTextField jTextDocumento;
    public javax.swing.JTextField jTextNomUsu;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlFechaAsign;
    private javax.swing.JLabel jlFechaRevoc;
    // End of variables declaration//GEN-END:variables
}
